apiVersion: v1
kind:  PersistentVolumeClaim
metadata:
  name: odoo-pvc
  namespace: icgroup
  labels:
    env: prod
    app: odoo
    type: local
spec:
  resources:
     requests: 
        storage: 5Gi
  accessMode:
    - ReadWriteOnce



