apiVersion: v1
kind:  PersistentVolume
metadata:
  name: postgres-pv
  namespace: icgroup
  labels:
    env: prod
    app: postgres
    type: local
spec:
  capacity:
    storage: 5Gi
  accessMode:
    - ReadWriteOnce
  PersistentVolumeReclaimPolicy: Delete
  storageClassName: manual
  HostPath:
   path: /data-postgres


